### ISSUE TITLE
Half-screen image.

### ISSUE THREAD

**Issue by LeonardSSH** [dothq/ntp#12]
**Describe the bug**
Half-screen picture.

**To Reproduce**
1. Go to [ntp.dothq.co](https://ntp.dothq.co/)

**Expected behavior**
A whole picture.

**Desktop (please complete the following information):**
 - Browser [Firefox]
 - Version [Developer Edition]

**Comment by johnpaulbin** [comment]
Does it reproduce on a different browser? Chrome is working fine on multiple high and low resolutions.

**Comment by EnderDev** [comment]
It seems to be only occurring in Firefox

**Comment by johnpaulbin** [comment]
on hold until API is fixed

**Comment by johnpaulbin** [comment]
API has been fixed, try to open the NTP page again and see what appears.

**Comment by johnpaulbin** [comment]
My guess it's the automatic background filling: when you zoom in or out it stays the same ratio.
Perhaps it has been fixed after the background API was fixed recently, could anyone prove this by going to [ntp.dothq.co](ntp.dothq.co)?
